### ISSUE TITLE
Raises an exception in ubuntu 

### ISSUE THREAD

**Issue by Kalebu** [pybash1/emuthon#1]
When I try to run main.py raises an error that looks as shown below;

```bash
kalebu@Jordankalebu:~/Work/Personal/cool project/emuthon$ python3 main.py 
Traceback (most recent call last):
  File "main.py", line 52, in <module>
    terminal(username, startDir)
  File "main.py", line 22, in terminal
    os.chdir(startDir)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\username'
```

**Comment by pybash1** [comment]
Yes. You have to change the `startDir` in config.ini to your home directory or any directory you wish the terminal to start in. The Default one is a windows directory since I made it on windows. :+1: Hope this helped you. I will add exception handlers soon. Thank you.
